#
# big_example Makefile
#

TOPDIR= ../

# Libraries
include $(TOPDIR)/Makefile.lib.incl
CXXFLAGS+= ${LIB_JON_TEST_FLAGS}
LIBS+= ${LIB_JON_TEST_LIBS}
LIB_DEP += ${LIB_JON_TEST_FILE}

# Targets
MAKE_EXE=big_example.exe
include $(TOPDIR)/Make/Makefile.incl
